### ISSUE TITLE
文档中多了一个多余的copy页面

### ISSUE THREAD

**Issue by Aloento** [huaweicloudDocs/cbr#8]
https://support.huaweicloud.com/api-cbr/ShowVaultResourceInstances_copy.html
https://support.huaweicloud.com/api-cbr/ShowVaultResourceInstances.html

这俩页面是同一个内容

**Comment by Weihongmin** [comment]
已收到问题，今天将会刷新，下掉第一个页面，感谢您的反馈。

**Comment by Weihongmin** [comment]
> https://support.huaweicloud.com/api-cbr/ShowVaultResourceInstances_copy.html https://support.huaweicloud.com/api-cbr/ShowVaultResourceInstances.html
> 
> 这俩页面是同一个内容

经评估，您反馈的有两个页面是同一个内容的问题已被接纳，计划于2022年7月19日前发布至华为云帮助中心，上线进展将在Github同步给您。

**Comment by Weihongmin** [comment]
您反馈的两个页面是同一个内容的问题在华为云帮助中心发布，详见https://support.huaweicloud.com/api-cbr/ShowVaultResourceInstances.html。感谢并期待您的再次反馈。
